# -------- Launch parameters --------

# Path to a file generated by 'python generate.py'
# describing an instance of the problem .
# Set to False is you wish to generate a new one

# PATH = 'sample_problems/sample.json'
PATH = False

# Random seed used for reproducibility
# Enter -1 for no seed
SEED = 42

# Whether to show plots at manual launch (python main.py)
PLOT = True

# 1 -> Only launch the Basic Evolutionary Algorithm
# 2 -> Only launch the Traditional Genetic Algorithm
# 3 -> Launch both and compare
VARIATIONS = 3

# Experimental visualization of solution (not very good :-D)
# Only works with VARIATIONS 2 and 3 and when calling main.py
VISUALIZE = False

# -------- Problem / Algorithm parameters --------

# The following four parameters only matter if you 
# aren't loading a file descirbing the problem.
# -- if PATH != False --
# Number of available tasks generated
TASK_COUNT = 500

# Number of available workers
WORKER_COUNT = 10

# Deadline for all tasks
DEADLINE = 50

# Maximum profit possible for task (forall profit, 0 <= profit <= MAX_PROFT)
MAX_PROFIT = 10
# -- endif --

# Baseline population size 
# (it oscillates around this value 
# due to mutations and crossing,
# but gets cuts down to match it eventually)
BASE_POPULATION_SIZE = 40

# Maximum number of iterations for the algorithm
MAX_ITER = 200

# Probability that a mutations is gonna take place
# at any crossing moment (Genetic Algorithm only)
MUTATION_PROB = 0.2

